repos:
  - repo: local # mise 経由で actionlint を使いたいので local
    hooks:
      - id: actionlint-system
        name: Lint GitHub Actions workflow files
        description: Runs system-installed actionlint to lint GitHub Actions workflow files
        language: system
        types: ["yaml"]
        files: ^\.github/workflows/
        entry: mise actionlint
